services:
  agora-server:
    image: ghcr.io/codegod100/agora-server:docker
    environment:
      - STORAGE_ENGINE=sqlite
      - GARDEN_DATABASE=/workspace/agora-server/data/garden.db
    ports:
      - "5017:5017"
    volumes:
      - data:/workspace/agora-server/data
  agora-bridge:
    image: ghcr.io/codegod100/agora-bridge:docker
    environment:
      - GARDEN_DIR=/workspace/sql-import/data/garden
      - GARDEN_DB=/workspace/sql-import/data/garden.db
    volumes:
      - data:/workspace/sql-import/data
    restart: 
      "always"

volumes:
  data:
